Fix python linting again.
- The function `delete_dataset` had been duplicated in the merge.
- Removed the other one to dismiss error:
  ./etsin_finder/qvain_light_service.py:238:5: F811 redefinition of unused 'delete_dataset' from line 210
- No side effects.